version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"